### ISSUE TITLE
Add "Mark as a spam" action in moderation

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/developer-community#102]
Today we have "Approve posting" and "Delete posting" action in moderation.
Let's add "Mark as a spam" action which will:
0. Release post from moderation and make it visible only to mods.
1. Grey the background to a "zombie style"
2. Add the tag "Spam" to the post which will let to group such posts into a collection to let us
1.  easily find all spam 
2. find all spammers
3. form a "museum of spam"

**Comment by evshvarov** [comment]
How could we find all spam posts?

**Comment by evshvarov** [comment]
New filter?

**Comment by lelikone** [comment]
Re: [intersystems-community/developer-community] Add "Mark as a spam" action in moderation (#102)



Здравствуйте, Evgeny.



С уважением, Алексей Канашевский                           
тел.: (3952) 76-11-33
e-mail:lelikone@mail.ru
-- 
Friday, January 11, 2019, 7:01:05 PM, Вы писали:





New filter?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.




--

**Comment by evshvarov** [comment]
Done
