### ISSUE TITLE
Can't add a translated post

### ISSUE THREAD

**Issue by CM-DC-ES** [intersystems-community/developer-community#251]
Hi!
Francisco Lopez wants to add the translation of this article: https://community.intersystems.com/post/advanced-url-mapping-rest
but it seems to have a bug or something similar...
Could you check it for us?
When we go to the tab "Translation", clic on "Add translated post" and get this text in the WYSIWYG mode:
![Captura de pantalla 2019-08-07 a las 11 44 49](https://user-images.githubusercontent.com/50864675/62612952-d0795400-b908-11e9-96f6-db0526cc54bb.png)
Thanks!
Esther

**Comment by lelikone** [comment]
@CM-DC-ES 
Hello, Esther. The article is written in the text format markdown. And unfortunately it is not convertible. You can simply clear the text field and copy the text from the article in the viewing mode. And then paste it into the editor.

**Comment by evshvarov** [comment]
Is it possible to translate/convert markdown in the future automatically?

ср, 7 авг. 2019 г. в 7:36, Aleksey Kanashevskiy <notifications@github.com>:

**Comment by CM-DC-ES** [comment]
Hi! I've followed your instructions and the article is already in Spanish, linked to Fabian's article. Just waiting for Curro's checking before being published. Thanks!

**Comment by lelikone** [comment]
@evshvarov 
If you convert on the fly using javascript, it's a pretty difficult task, because forward and backward conversion due to format nuances will give a mixed result. If you do the conversion when generating a post, you can, but maybe someone will write to markdown, then he does not need the conversion. I do not see an easy solution yet.
